In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
## Load the dataset
data=pd.read_csv("Mall_Customers.csv")
data.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [ ]:
## Preprocess the data
## Drop inrelavent fatures
data=data.drop(['CustomerID'],axis=1)

KeyError: "['CustomerID'] not found in axis"

In [5]:
## Preprocess the data
## Drop inrelavent fatures
data.head()

   Gender  Age  Annual Income (k$)  Spending Score (1-100)
0    Male   19                  15                      39
1    Male   21                  15                      81
2  Female   20                  16                       6
3  Female   23                  16                      77
4  Female   31                  17                      40

In [6]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data.head()

   Gender  Age  Annual Income (k$)  Spending Score (1-100)
0       1   19                  15                      39
1       1   21                  15                      81
2       0   20                  16                       6
3       0   23                  16                      77
4       0   31                  17                      40

In [7]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

In [8]:
data['HighSpender'] = (data['Spending Score (1-100)'] > 50).astype(int)

In [9]:
data.head()

   Gender  Age  Annual Income (k$)  Spending Score (1-100)  HighSpender
0       1   19                  15                      39            0
1       1   21                  15                      81            1
2       0   20                  16                       6            0
3       0   23                  16                      77            1
4       0   31                  17                      40            0

In [10]:
# Divide the dataset into features and target
X = data.drop('HighSpender', axis=1)
y = data['HighSpender']

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_train

array([[-0.87077078,  0.73027906, -0.24190423, -0.37113766],
       [ 1.14840785, -0.50042667,  2.39455436,  0.84383985],
       [-0.87077078, -0.21084885, -0.8644014 , -0.97862642],
       [-0.87077078,  1.09225134, -1.19395872, -1.43424298],
       [-0.87077078,  0.07872897,  0.30735798,  0.23635109],
       [-0.87077078, -0.2832433 ,  2.17484948,  1.03368009],
       [-0.87077078, -1.15197676, -1.15734124,  1.33742446],
       [-0.87077078, -0.2832433 , -1.37704612,  1.75507298],
       [-0.87077078, -0.50042667,  0.56368034,  1.33742446],
       [-0.87077078,  1.16464579, -0.13205179,  0.23635109],
       [-0.87077078, -1.51394904,  0.16088805, -0.14332938],
       [ 1.14840785, -0.21084885,  0.96647262,  1.5272647 ],
       [-0.87077078, -1.22437122, -1.59675101,  0.91977594],
       [ 1.14840785,  0.29591233,  0.38059294, -0.63691399],
       [-0.87077078,  0.73027906,  0.16088805,  0.27431914],
       [-0.87077078,  1.52661807, -0.38837415,  0.160415  ],
       [-0.87077078,  1.3094347 ,  0.52706286, -1.77595541],
       [ 1.14840785,  0.65788461,  0.01441813, -0.37113766],
       [ 1.14840785, -0.21084885,  0.96647262, -1.58611517],
       [-0.87077078,  0.58549015, -0.02219935, -0.18129743],
       [ 1.14840785, -0.50042667,  0.96647262,  0.42619133],
       [-0.87077078, -0.86239894, -0.02219935, -0.06739328],
       [-0.87077078, -1.29676567, -1.12072376,  0.8058718 ],
       [-0.87077078,  1.38182916, -1.48689856, -1.39627494],
       [-0.87077078, -1.29676567, -1.01087132,  1.10961618],
       [-0.87077078,  0.80267352,  0.23412302,  0.19838305],
       [ 1.14840785,  0.65788461, -0.79116644, -0.59894595],
       [-0.87077078, -0.21084885,  1.55235231,  1.26148837],
       [-0.87077078,  2.10577371, -0.05881683,  0.12244695],
       [-0.87077078,  0.36830679,  0.4538279 , -1.70001932],
       [ 1.14840785, -0.42803221, -0.68131399,  0.31228719],
       [ 1.14840785,  0.07872897,  0.38059294,  1.64116884],
       [ 1.14840785, -1.44155458,  0.74676774, -1.77595541],
       [ 1.14840785, -1.07958231, -0.82778392,  1.5272647 ],
       [-0.87077078,  0.87506797,  0.23412302, -0.33316961],
       [ 1.14840785, -1.44155458,  0.12427057, -0.21926547],
       [-0.87077078,  0.44070124, -1.19395872, -0.75081813],
       [-0.87077078, -0.2832433 ,  0.49044538,  0.76790376],
       [-0.87077078, -1.15197676,  0.05103561, -0.40910571],
       [-0.87077078, -1.44155458,  0.08765309,  0.08447891],
       [-0.87077078, -1.36916013, -1.63336849, -1.73798736],
       [ 1.14840785,  0.07872897, -0.24190423, -0.14332938],
       [-0.87077078,  0.80267352, -0.75454896,  0.12244695],
       [ 1.14840785, -0.79000449,  1.47911735,  0.61603157],
       [-0.87077078, -0.50042667,  1.55235231,  0.65399961],
       [ 1.14840785,  0.65788461, -0.24190423, -0.21926547],
       [-0.87077078, -0.71761003,  0.67353278,  1.18555228],
       [-0.87077078,  0.22351788, -0.97425384, -1.32033884],
       [-0.87077078, -0.35563776,  1.55235231, -1.09253056],
       [ 1.14840785, -1.44155458, -0.53484407,  0.12244695],
       [-0.87077078,  0.5130957 , -1.30381116, -1.77595541],
       [ 1.14840785, -0.50042667,  0.52706286,  1.56523275],
       [-0.87077078,  0.73027906,  0.05103561, -0.14332938],
       [ 1.14840785, -1.51394904, -1.01087132,  1.5272647 ],
       [-0.87077078, -0.2832433 , -1.52351604,  1.79304103],
       [-0.87077078,  0.58549015,  2.17484948, -1.35830689],
       [-0.87077078, -0.64521558,  0.6369153 ,  0.8058718 ],
       [-0.87077078, -0.2832433 , -1.56013352, -1.73798736],
       [ 1.14840785, -0.2832433 , -1.19395872,  0.35025524],
       [ 1.14840785, -0.86239894,  0.23412302,  0.160415  ],
       [-0.87077078, -0.57282112, -1.59675101, -0.44707376],
       [ 1.14840785,  1.01985688, -1.01087132, -1.81392346],
       [-0.87077078, -0.79000449,  0.56368034, -0.44707376],
       [ 1.14840785, -0.79000449,  0.60029782,  1.71710494],
       [ 1.14840785,  1.9609848 ,  0.08765309, -0.14332938],
       [ 1.14840785, -1.00718785,  0.60029782, -1.51017908],
       [ 1.14840785,  2.03337925, -1.52351604, -1.43424298],
       [-0.87077078,  2.03337925, -0.49822659,  0.00854281],
       [-0.87077078, -0.06605994,  0.12427057, -0.37113766],
       [ 1.14840785,  0.65788461,  0.60029782, -0.59894595],
       [ 1.14840785,  0.22351788,  0.92985514, -1.2064347 ],
       [ 1.14840785, -1.44155458, -1.66998597, -0.4850418 ],
       [ 1.14840785, -0.50042667,  2.79734664, -1.2823708 ],
       [-0.87077078, -0.06605994,  0.6369153 ,  0.91977594],
       [ 1.14840785,  2.25056262, -0.42499163,  0.12244695],
       [ 1.14840785,  0.00633451,  0.30735798,  1.48929665],
       [ 1.14840785,  1.74380143, -0.46160911, -0.02942524],
       [-0.87077078,  0.73027906, -0.79116644, -0.90269032],
       [-0.87077078, -0.57282112,  0.74676774,  1.56523275],
       [-0.87077078,  0.07872897, -1.15734124, -0.78878618],
       [-0.87077078,  1.88859034, -0.82778392, -0.63691399],
       [ 1.14840785,  2.10577371,  0.08765309, -0.33316961],
       [-0.87077078, -0.86239894,  0.6369153 ,  1.41336056],
       [ 1.14840785, -0.13845439,  0.6369153 , -1.9278276 ],
       [ 1.14840785, -0.71761003, -1.19395872,  1.14758423],
       [ 1.14840785, -0.57282112, -1.30381116,  0.8058718 ],
       [-0.87077078,  0.15112342,  1.40588239, -0.4850418 ],
       [-0.87077078, -0.50042667,  0.60029782,  0.84383985],
       [ 1.14840785, -0.06605994, -0.24190423,  0.12244695],
       [-0.87077078, -1.36916013, -0.8644014 ,  0.8818079 ],
       [-0.87077078, -0.21084885,  0.96647262, -0.94065837],
       [-0.87077078, -0.86239894, -0.75454896, -0.18129743],
       [-0.87077078, -0.50042667, -0.02219935, -0.37113766],
       [-0.87077078,  0.58549015,  0.6369153 , -1.35830689],
       [-0.87077078, -0.57282112, -0.79116644,  0.35025524],
       [ 1.14840785, -1.44155458,  0.49044538, -1.58611517],
       [-0.87077078, -1.15197676, -1.63336849,  0.95774399],
       [-0.87077078, -1.29676567,  0.05103561, -0.37113766],
       [ 1.14840785,  1.45422361, -0.64469651,  0.31228719],
       [-0.87077078, -0.57282112,  0.41721042,  0.72993571],
       [-0.87077078, -0.13845439,  1.33264743, -0.75081813],
       [ 1.14840785,  1.45422361,  1.18617751, -1.43424298],
       [ 1.14840785, -0.64521558,  1.40588239,  1.71710494],
       [-0.87077078, -0.57282112, -0.75454896, -0.37113766],
       [ 1.14840785,  1.3094347 , -0.24190423, -0.02942524],
       [-0.87077078,  0.73027906, -1.01087132, -1.43424298],
       [-0.87077078, -1.15197676, -1.56013352,  1.60320079],
       [ 1.14840785,  1.88859034,  0.08765309,  0.00854281],
       [ 1.14840785, -1.51394904, -0.05881683, -0.40910571],
       [-0.87077078,  0.5130957 , -0.24190423, -0.29520157],
       [ 1.14840785,  1.38182916,  1.0030901 , -1.39627494],
       [-0.87077078, -0.50042667,  1.33264743,  1.29945642],
       [-0.87077078,  0.80267352, -0.09543431, -0.21926547],
       [ 1.14840785,  1.81619589, -1.52351604, -1.8518915 ],
       [-0.87077078, -1.07958231, -1.48689856,  0.95774399],
       [ 1.14840785,  1.01985688, -0.53484407, -0.21926547],
       [ 1.14840785, -0.79000449,  0.96647262,  0.8818079 ],
       [ 1.14840785,  0.00633451,  0.38059294,  0.8818079 ],
       [ 1.14840785, -1.36916013, -1.45028108,  0.54009547],
       [-0.87077078,  1.52661807, -0.38837415, -0.10536133],
       [-0.87077078, -0.64521558,  1.0030901 ,  1.29945642],
       [ 1.14840785, -1.36916013,  0.4538279 , -1.77595541],
       [-0.87077078, -0.42803221,  0.92985514,  1.64116884],
       [-0.87077078, -0.71761003,  1.36926491,  1.37539251],
       [-0.87077078,  1.09225134, -0.49822659,  0.27431914],
       [-0.87077078,  0.80267352, -0.64469651, -0.25723352],
       [ 1.14840785,  1.09225134,  0.08765309, -0.21926547],
       [-0.87077078,  0.73027906, -0.68131399,  0.00854281],
       [-0.87077078,  0.44070124,  2.39455436, -0.90269032],
       [-0.87077078, -0.86239894, -0.53484407, -0.02942524],
       [-0.87077078, -0.71761003, -0.75454896, -0.37113766],
       [-0.87077078, -0.35563776, -0.09543431,  0.31228719],
       [ 1.14840785, -1.00718785, -1.34042864,  0.8058718 ],
       [ 1.14840785,  2.17816816, -0.60807903, -0.21926547],
       [-0.87077078,  1.23704025,  0.67353278, -0.63691399],
       [ 1.14840785, -0.42803221,  1.91852711, -1.66205127],
       [ 1.14840785, -0.06605994,  0.38059294,  0.8818079 ],
       [-0.87077078, -0.64521558, -0.97425384,  0.8058718 ],
       [-0.87077078, -0.64521558,  0.6369153 ,  0.99571204],
       [-0.87077078, -0.06605994,  1.91852711,  1.48929665],
       [ 1.14840785, -1.29676567, -1.66998597,  1.10961618],
       [-0.87077078, -0.57282112, -0.64469651,  0.08447891],
       [ 1.14840785, -0.35563776,  0.6369153 ,  1.45132861],
       [ 1.14840785,  0.58549015,  0.38059294, -1.62408322],
       [ 1.14840785,  0.00633451,  0.6369153 ,  1.37539251],
       [ 1.14840785, -0.9347934 ,  0.05103561,  0.12244695],
       [ 1.14840785, -1.36916013,  0.01441813, -0.10536133],
       [-0.87077078,  1.74380143,  0.16088805, -0.33316961],
       [-0.87077078, -1.22437122, -0.13205179,  0.12244695],
       [ 1.14840785,  1.45422361, -0.24190423, -0.18129743],
       [-0.87077078, -0.06605994,  0.23412302, -0.44707376],
       [ 1.14840785, -0.64521558,  2.79734664,  1.18555228],
       [ 1.14840785, -0.2832433 , -1.34042864, -0.63691399],
       [-0.87077078,  0.15112342,  1.55235231, -1.32033884],
       [-0.87077078,  0.58549015, -0.42499163, -0.37113766],
       [-0.87077078,  1.9609848 ,  0.08765309, -0.06739328],
       [ 1.14840785, -0.13845439, -1.48689856, -1.47221103],
       [ 1.14840785,  0.65788461, -0.02219935, -0.10536133],
       [ 1.14840785, -0.2832433 ,  1.18617751,  1.45132861],
       [ 1.14840785,  2.03337925,  0.05103561,  0.27431914]])

In [27]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_train)

In [29]:
with open('scaler.pkl','wb') as file:
    pickle.dump('scaler',file)

In [13]:
data

     Gender  Age  Annual Income (k$)  Spending Score (1-100)  HighSpender
0         1   19                  15                      39            0
1         1   21                  15                      81            1
2         0   20                  16                       6            0
3         0   23                  16                      77            1
4         0   31                  17                      40            0
..      ...  ...                 ...                     ...          ...
195       0   35                 120                      79            1
196       0   45                 126                      28            0
197       1   32                 126                      74            1
198       1   32                 137                      18            0
199       1   30                 137                      83            1

[200 rows x 5 columns]

## ANN Implementation

In [14]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [15]:
(X_train.shape[1],)

(4,)

In [16]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## HL1 Connected with input layer
    Dense(32,activation='relu'), ## HL2
    Dense(1,activation='sigmoid') ## Output Layer
])

C:\Users\chuda\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,433 (9.50 KB)

 Trainable params: 2,433 (9.50 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [19]:
## Compile the Model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [20]:
## Set Up the TensorBoard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir="logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [21]:
## Set Up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [22]:
## Training The Model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 61ms/step - accuracy: 0.6039 - loss: 0.6529 - val_accuracy: 0.9000 - val_loss: 0.4110
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.8972 - loss: 0.3928 - val_accuracy: 0.9500 - val_loss: 0.2529
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.9932 - loss: 0.1903 - val_accuracy: 0.9750 - val_loss: 0.1701
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9907 - loss: 0.1246 - val_accuracy: 0.9500 - val_loss: 0.1514
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9727 - loss: 0.0658 - val_accuracy: 0.9750 - val_loss: 0.1047
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0466 - val_accuracy: 1.0000 - val_loss: 0.0663
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.0338 - val_accuracy: 1.0000 - val_loss: 0.0639
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9979 - loss: 0.0253 - val_accuracy: 0.9500 - val_loss: 0.1023
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.9979 - loss: 0.0183 - val_accuracy: 0.9500 - val_loss: 0.0645
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.0178 - val_accuracy: 0.9750 - val_loss: 0.0523
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.0076 - val_accuracy: 0.9750 - val_loss: 0.0482
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.0088 - val_accuracy: 0.9750 - val_loss: 0.0493
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0060 - val_accuracy: 0.9500 - val_loss: 0.0585
Epoch 14/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0093 - val_accuracy: 0.9750 - val_loss: 0.0665
Epoch 15/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.0049 - val_accuracy: 0.9750 - val_loss: 0.0527
Epoch 16/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.0067 - val_accuracy: 0.9750 - val_loss: 0.0434
Epoch 17/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 0.0045 - val_accuracy: 0.9750 - val_loss: 0.0464
Epoch 18/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.0037 - val_accuracy: 0.9750 - val_loss: 0.0415
Epoch 19/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.0022 - val_accuracy: 0.9750 - val_loss: 0.0450
Epoch 20/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.9750 - val_loss: 0.0605
Epoch 21/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0032 - val_accuracy: 0.9750 - val_loss: 0.0489
Epoch 22/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.0021 - val_accuracy: 0.9750 - val_loss: 0.0393
Epoch 23/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 0.9750 - val_loss: 0.0441
Epoch 24/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0023 - val_accuracy: 0.9750 - val_loss: 0.0453
Epoch 25/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.9750 - val_loss: 0.0444
Epoch 26/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.9750 - val_loss: 0.0400
Epoch 27/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 0.9750 - val_loss: 0.0537
Epoch 28/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 1.0000 - loss: 0.0019 - val_accuracy: 0.9750 - val_loss: 0.0551
Epoch 29/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.9750 - val_loss: 0.0378
Epoch 30/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 1.0000 - loss: 0.0016 - val_accuracy: 0.9750 - val_loss: 0.0372
Epoch 31/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 0.9750 - val_loss: 0.0475
Epoch 32/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.0014 - val_accuracy: 0.9750 - val_loss: 0.0416
Epoch 33/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 8.5875e-04 - val_accuracy: 0.9750 - val_loss: 0.0473
Epoch 34/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9750 - val_loss: 0.0443
Epoch 35/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 7.8205e-04 - val_accuracy: 0.9750 - val_loss: 0.0399
Epoch 36/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 1.0000 - loss: 0.0012 - val_accuracy: 0.9750 - val_loss: 0.0429
Epoch 37/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 1.0000 - loss: 8.4423e-04 - val_accuracy: 0.9750 - val_loss: 0.0437
Epoch 38/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 1.0000 - loss: 8.0803e-04 - val_accuracy: 0.9750 - val_loss: 0.0435
Epoch 39/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.0011 - val_accuracy: 0.9750 - val_loss: 0.0458
Epoch 40/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 6.7020e-04 - val_accuracy: 0.9750 - val_loss: 0.0407

In [30]:
with open('scaler.pkl','wb') as file:
    pickle.dump('scaler',file)

In [23]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [24]:
## Load Tensorboard Extension
%load_ext tensorboard

In [26]:
%tensorboard --logs logs/fit

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.